### ISSUE TITLE
Recomendacion: Adicion de seccion de tecnologias utilizadas

### ISSUE THREAD

**Issue by Niccolello** [cnsvilca/portfolio-template#1]
![image](https://user-images.githubusercontent.com/107757272/177633324-a4883375-fa03-4ea6-a551-a13edc00e1a3.png)
con el objetivo de que el usuario que haga uso del portfolio tnga mas informacion de su experiencia.
Saludos!

**Comment by cnsvilca** [comment]
Hola, sí por favor, me parece conveniente te lo agradecería 👍

**Comment by cnsvilca** [comment]
Muchas gracias @Niccolello por tu aporte, quedó impecable!! saludos✋
